In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
pd.set_option("display.float_format", "{:,.2f}".format)

In [2]:
customers = pd.read_csv("E:/General_DS_project/Data/Raw/customers.csv")
transactions = pd.read_csv("E:/General_DS_project/Data/Raw/transactions.csv")
activity_logs = pd.read_csv("E:/General_DS_project/Data/Raw/activity_logs.csv")

In [3]:
print(customers.info())
print(transactions.info())
print(activity_logs.info())

<class 'pandas.DataFrame'>
RangeIndex: 53000 entries, 0 to 52999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      53000 non-null  str
 1   age              47698 non-null  float64
 2   gender           53000 non-null  str
 3   country          53000 non-null  str
 4   employment_type  50357 non-null  str
 5   income           47710 non-null  float64
 6   account_type     50880 non-null  str
 7   signup_date      53000 non-null  str
 8   customer_status  53000 non-null  str
dtypes: float64(2), str(7)
memory usage: 6.2 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      150000 non-null  str
 1   customer_id         150000 non-null  str
 2   payment_date        150000 non-null  str
 3   amount              147000 non-null  float64
 4   payment_mode        145000 non-null  str
 5   transaction_status  150000 non-null  str
 6   transaction_type    147500 non-null  str
dtypes: float64(1), str(6)
memory usage: 14.9 MB
None
<class 'pandas.DataFrame'>
RangeIndex: 305000 entries, 0 to 304999
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   activity_id         305000 non-null  str
 1   customer_id         305000 non-null  str
 2   activity_timestamp  305000 non-null  str
 3   activity_type       297883 non-null  str
 4   device_type         294814 non-null  str
 5   platform            305000 non-null  str
 6   session_duration    299916 non-null  float64
dtypes: float64(1), str(6)
memory usage: 30.1 MB
None

In [4]:
print(customers.shape)
print(transactions.shape)
print(activity_logs.shape)

(53000, 9)
(150000, 7)
(305000, 7)

In [5]:
print(customers.columns)
print(transactions.columns)
print(activity_logs.columns)

Index(['customer_id', 'age', 'gender', 'country', 'employment_type', 'income',
       'account_type', 'signup_date', 'customer_status'],
      dtype='str')
Index(['transaction_id', 'customer_id', 'payment_date', 'amount',
       'payment_mode', 'transaction_status', 'transaction_type'],
      dtype='str')
Index(['activity_id', 'customer_id', 'activity_timestamp', 'activity_type',
       'device_type', 'platform', 'session_duration'],
      dtype='str')

In [6]:
customers["gender"].value_counts(dropna = False)

gender
Male      23961
Female    23316
Other      2534
male        383
O           377
F           359
female      359
other       355
m           350
M           340
f           337
OTH         329
Name: count, dtype: int64

In [7]:
customers["country"].value_counts(dropna = False)

country
India             17537
USA                9911
UK                 5046
Canada             3987
Germany            3979
Australia          3471
Singapore          2953
UAE                2947
United States       172
U.S.                170
GERMANY             169
singapore           163
United Kingdom      161
india               159
uae                 155
Ger                 154
uk                  153
CAN                 151
INDIA               147
U.K.                146
usa                 146
australia           145
Aus                 143
Emirates            142
Ind                 142
u.a.e               141
germany             139
SG                  139
canada              132
Name: count, dtype: int64

In [8]:
customers["employment_type"].value_counts(dropna = False)

employment_type
Employed          22652
Self-Employed      6992
Student            5775
Business Owner     4727
Retired            3791
Unemployed         3245
NaN                2643
STUDENT             264
UNEMPLOYED          257
unemployed          256
student             251
SELF-EMPLOYED       232
employed            232
BUSINESS OWNER      230
BusinessOwner       220
retired             212
RETIRED             212
self employed       210
EMPLOYED            204
business owner      201
Self employed       194
Name: count, dtype: int64

In [9]:
customers["account_type"].value_counts(dropna = False)

account_type
Savings            26542
Salary              9643
Current             7285
Premium             4748
NaN                 2120
CURRENT              274
saving               253
SAVINGS              250
PREMIUM              246
premium              244
salary account       242
current              240
savings              239
salary               237
SALARY               231
premium account      206
Name: count, dtype: int64

In [10]:
customers["customer_status"].value_counts(dropna = False)

customer_status
Active       35204
Inactive      7571
Closed        5034
Suspended     2553
inactive       361
SUSPENDED      348
ACTIVE         343
closed         330
suspended      323
active         316
CLOSED         316
INACTIVE       301
Name: count, dtype: int64

In [11]:
customers["customer_status"].head()

0    Inactive
1      active
2    Inactive
3    Inactive
4    Inactive
Name: customer_status, dtype: str

In [12]:
customers[["age", "income"]].describe()

                age        income
count  47698.000000  4.771000e+04
mean      26.265588  9.956746e+05
std       14.403575  1.148737e+06
min      -10.000000 -9.998600e+04
25%       19.000000  3.334531e+05
50%       25.000000  7.213808e+05
75%       31.000000  1.218376e+06
max      120.000000  1.000000e+07

In [13]:
customers["signup_date"].head()

0    2024-02-02
1    2024-12-31
2    2026-09-14
3    2023-02-28
4    2024-02-14
Name: signup_date, dtype: str

In [14]:
customers["signup_date"] = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

In [17]:
customers["signup_date"].dtype

dtype('<M8[us]')

In [18]:
customers["signup_date"].isna().sum()

np.int64(0)

In [19]:
customers["signup_date"].min()
customers["signup_date"].max()

Timestamp('2027-08-19 00:00:00')

In [20]:
customers.isnull().sum()

customer_id           0
age                5302
gender                0
country               0
employment_type    2643
income             5290
account_type       2120
signup_date           0
customer_status       0
dtype: int64

In [21]:
customers.isnull().mean() * 100

customer_id         0.000000
age                10.003774
gender              0.000000
country             0.000000
employment_type     4.986792
income              9.981132
account_type        4.000000
signup_date         0.000000
customer_status     0.000000
dtype: float64

In [23]:
customers["age"].describe()

count    47698.000000
mean        26.265588
std         14.403575
min        -10.000000
25%         19.000000
50%         25.000000
75%         31.000000
max        120.000000
Name: age, dtype: float64

In [24]:
customers["age"].value_counts().sort_index().head(20)

age
-10.0     103
-9.0      109
-8.0      112
-7.0       94
-6.0      114
-5.0       99
-4.0      108
-3.0      100
-2.0      108
-1.0      107
 0.0     1051
 18.0    9319
 19.0    1621
 20.0    1828
 21.0    1936
 22.0    1955
 23.0    2166
 24.0    2302
 25.0    2191
 26.0    2252
Name: count, dtype: int64

In [25]:
customers["age"].value_counts().sort_index().tail(20)

age
101.0    23
102.0    27
103.0    41
104.0    20
105.0    20
106.0    24
107.0    27
108.0    37
109.0    26
110.0    22
111.0    34
112.0    29
113.0    23
114.0    22
115.0    27
116.0    24
117.0    29
118.0    34
119.0    40
120.0    21
Name: count, dtype: int64

In [28]:
invalid_age_mask = (
    (customers["age"] < 18) |
    (customers["age"] > 80)
)

invalid_age_mask.sum()

np.int64(3171)

In [29]:
customers.loc[
    ~invalid_age_mask,
    "age"
].describe()

count    44527.000000
mean        25.854223
std          6.749772
min         18.000000
25%         20.000000
50%         25.000000
75%         30.000000
max         58.000000
Name: age, dtype: float64

In [41]:
invalid_age_idx = customers.index[invalid_age_mask]
customers.loc[invalid_age_idx,"age"] = np.nan
age_median = customers["age"].median()
customers["age"] = customers["age"].fillna(age_median)

In [42]:
customers["age"].describe()

count    53000.000000
mean        25.717660
std          6.194659
min         18.000000
25%         21.000000
50%         25.000000
75%         29.000000
max         58.000000
Name: age, dtype: float64

In [43]:
customers["age"].isna().sum()

np.int64(0)

In [44]:
customers["age"].describe()

count    53000.000000
mean        25.717660
std          6.194659
min         18.000000
25%         21.000000
50%         25.000000
75%         29.000000
max         58.000000
Name: age, dtype: float64

In [54]:
print(customers["income"].describe())

count       47,710.00
mean       995,674.60
std      1,148,737.05
min        -99,986.00
25%        333,453.14
50%        721,380.80
75%      1,218,375.96
max     10,000,000.00
Name: income, dtype: float64

In [47]:
customers["income"].value_counts().sort_index().head(20)

income
-99986.0    1
-99883.0    1
-99845.0    1
-99815.0    1
-99758.0    1
-99711.0    1
-99699.0    1
-99687.0    1
-99647.0    1
-99576.0    2
-99532.0    1
-99455.0    1
-99436.0    1
-99393.0    1
-99284.0    1
-99271.0    1
-99251.0    1
-99187.0    1
-99172.0    1
-99127.0    1
Name: count, dtype: int64

In [48]:
customers["income"].value_counts().sort_index().tail(20)

income
9348522.98       1
9351392.13       1
9382863.34       1
9415106.25       1
9427000.38       1
9428363.47       1
9448749.68       1
9462353.14       1
9475689.18       1
9579132.79       1
9595038.98       1
9642730.63       1
9684716.51       1
9762820.80       1
9821267.92       1
9842436.29       1
9929029.92       1
9952196.61       1
9955429.55       1
10000000.00    132
Name: count, dtype: int64

In [50]:
invalid_income_mask = (
    (customers["income"] < 0))

In [55]:
customers.loc[
    ~invalid_income_mask,
    "income"].describe()

count       45,589.00
mean     1,044,298.07
std      1,152,288.77
min         20,072.66
25%        401,146.75
50%        752,651.07
75%      1,254,019.39
max     10,000,000.00
Name: income, dtype: float64

In [58]:
invalid_income_idx = customers.index[invalid_income_mask]
customers.loc[invalid_income_idx,"income"] = np.nan

In [61]:
(customers["income"] < 0).sum()

np.int64(0)

In [62]:
income_median = customers["income"].median()
customers["income"] = customers["income"].fillna(income_median)

In [63]:
customers["income"].describe()

count       53,000.00
mean     1,003,517.01
std      1,073,468.41
min         20,072.66
25%        467,763.76
50%        752,651.07
75%      1,140,015.72
max     10,000,000.00
Name: income, dtype: float64

In [65]:
customers["employment_type"].value_counts(dropna = False)

employment_type
Employed          22652
Self-Employed      6992
Student            5775
Business Owner     4727
Retired            3791
Unemployed         3245
NaN                2643
STUDENT             264
UNEMPLOYED          257
unemployed          256
student             251
SELF-EMPLOYED       232
employed            232
BUSINESS OWNER      230
BusinessOwner       220
retired             212
RETIRED             212
self employed       210
EMPLOYED            204
business owner      201
Self employed       194
Name: count, dtype: int64

In [66]:
customers["employment_type"].value_counts(normalize=True, dropna=False) * 100

employment_type
Employed         42.74
Self-Employed    13.19
Student          10.90
Business Owner    8.92
Retired           7.15
Unemployed        6.12
NaN               4.99
STUDENT           0.50
UNEMPLOYED        0.48
unemployed        0.48
student           0.47
SELF-EMPLOYED     0.44
employed          0.44
BUSINESS OWNER    0.43
BusinessOwner     0.42
retired           0.40
RETIRED           0.40
self employed     0.40
EMPLOYED          0.38
business owner    0.38
Self employed     0.37
Name: proportion, dtype: float64

In [69]:
employment_type_mapping = {
    "Employed" : "Employed",
    "employed" : "Employed",
    "EMPLOYED" : "Employed",
    "Self-Employed" : "Self-Employed",
    "Student" : "Student",
    "Business Owner" : "Business Owner",
    "Retired" : "Retired",
    "Unemployed" : "Unemployed",
    "NaN" : "NaN",
    "STUDENT" : "Student",
    "UNEMPLOYED" : "Unemployed",
    "student" : "Student",
    "SELF-EMPLOYED" : "Self-Employed",
    "BUSINESS OWNER" : "Business Owner",
    "retired" : "Retired",
    "RETIRED" : "Retired",
    "self employed" : "Self-Employed",
    "business owner" : "Business Owner",
    "Self employed" : "Self-Employed"}
customers["employment_type"] = customers["employment_type"].map(employment_type_mapping)

In [70]:
customers["employment_type"].value_counts(dropna = False)

employment_type
Employed          23088
NaN                8894
Self-Employed      7628
Business Owner     5158
Retired            4215
Unemployed         3502
Student             515
Name: count, dtype: int64

In [71]:
customers["employment_type"].value_counts(normalize = True,dropna = False) * 100

employment_type
Employed         43.56
NaN              16.78
Self-Employed    14.39
Business Owner    9.73
Retired           7.95
Unemployed        6.61
Student           0.97
Name: proportion, dtype: float64

In [72]:
customers[
    customers["employment_type"].astype(str).str.contains(
        "student",
        case=False,
        na=False
    )
]["employment_type"].value_counts()

employment_type
Student    515
Name: count, dtype: int64

In [73]:
customers_2 = pd.read_csv("E:/General_DS_project/Data/Raw/customers.csv")

In [74]:
customers_2["employment_type"].value_counts(dropna = False)

employment_type
Employed          22652
Self-Employed      6992
Student            5775
Business Owner     4727
Retired            3791
Unemployed         3245
NaN                2643
STUDENT             264
UNEMPLOYED          257
unemployed          256
student             251
SELF-EMPLOYED       232
employed            232
BUSINESS OWNER      230
BusinessOwner       220
retired             212
RETIRED             212
self employed       210
EMPLOYED            204
business owner      201
Self employed       194
Name: count, dtype: int64

In [75]:
customers["employment_type"] = customers_2["employment_type"].copy()

In [76]:
employment_type_mapping = {
    "Employed": "Employed",
    "employed": "Employed",
    "EMPLOYED": "Employed",

    "Self-Employed": "Self-Employed",
    "SELF-EMPLOYED": "Self-Employed",
    "self employed": "Self-Employed",
    "Self employed": "Self-Employed",

    "Student": "Student",
    "STUDENT": "Student",
    "student": "Student",

    "Business Owner": "Business Owner",
    "BUSINESS OWNER": "Business Owner",
    "business owner": "Business Owner",
    "BusinessOwner": "Business Owner",

    "Retired": "Retired",
    "retired": "Retired",
    "RETIRED": "Retired",

    "Unemployed": "Unemployed",
    "UNEMPLOYED": "Unemployed",
    "unemployed": "Unemployed"
}

customers["employment_type"] = (
    customers["employment_type"].map(employment_type_mapping)
)

In [78]:
customers["employment_type"].value_counts(normalize = True,dropna = False) * 100

employment_type
Employed         43.56
Self-Employed    14.39
Student          11.87
Business Owner   10.15
Retired           7.95
Unemployed        7.09
NaN               4.99
Name: proportion, dtype: float64

In [79]:
customers["employment_type"].mode()

0    Employed
Name: employment_type, dtype: str

In [80]:
"Unknown" in customers["employment_type"].unique()

False

In [82]:
customers["employment_type"].isna().sum()

np.int64(2643)

In [83]:
customers["employment_type"] = customers["employment_type"].fillna("Unknown")

In [84]:
customers["employment_type"].isnull().sum()

np.int64(0)

In [85]:
customers["employment_type"].value_counts(normalize = True,dropna = False) * 100

employment_type
Employed         43.56
Self-Employed    14.39
Student          11.87
Business Owner   10.15
Retired           7.95
Unemployed        7.09
Unknown           4.99
Name: proportion, dtype: float64

In [86]:
customers["account_type"].value_counts(normalize = True,dropna = False) * 100

account_type
Savings           50.08
Salary            18.19
Current           13.75
Premium            8.96
NaN                4.00
CURRENT            0.52
saving             0.48
SAVINGS            0.47
PREMIUM            0.46
premium            0.46
salary account     0.46
current            0.45
savings            0.45
salary             0.45
SALARY             0.44
premium account    0.39
Name: proportion, dtype: float64

In [90]:
customers["account_type"].nunique()

15

In [92]:
account_type_mapping = {
    "Savings" : "Savings",
    "savings" : "Savings",
    "SAVINGS" : "Savings",
    "saving" : "Savings",

    "Salary" : "Salary",
    "salary account" : "Salary",
    "SALARY" : "Salary",

    "Current" : "Current",
    "CURRENT" : "Current",
    "current" : "Current",

    "Premium" : "Premium",
    "PREMIUM" : "Premium",
    "premium" : "Premium",
    "premium account" : "Premium"
}
customers["account_type"] = customers["account_type"].map(account_type_mapping)

In [93]:
customers["account_type"].value_counts(normalize = True,dropna = False) * 100

account_type
Savings   51.48
Salary    19.09
Current   14.72
Premium   10.27
NaN        4.45
Name: proportion, dtype: float64

In [94]:
customers["customer_status"].value_counts(dropna = False)

customer_status
Active       35204
Inactive      7571
Closed        5034
Suspended     2553
inactive       361
SUSPENDED      348
ACTIVE         343
closed         330
suspended      323
active         316
CLOSED         316
INACTIVE       301
Name: count, dtype: int64

In [95]:
customers["customer_status"].nunique()

12

In [96]:
customer_status_mapping = {
    "Active" : "Active",
    "ACTIVE" : "Active",
    "active" : "Active",

    "Inactive" : "Inactive",
    "inactive" : "Inactive",
    "INACTIVE" : "Inactive",

    "Closed" : "Closed",
    "closed" : "Closed",
    "CLOSED" : "Closed",

    "Suspended" : "Suspended",
    "SUSPENDED" : "Suspended",
    "suspended" : "Suspended",
}
customers["customer_status"] = customers["customer_status"].map(customer_status_mapping)

In [99]:
customers["customer_status"].value_counts(dropna = False)

customer_status
Active       35863
Inactive      8233
Closed        5680
Suspended     3224
Name: count, dtype: int64

In [98]:
customers["customer_status"].value_counts(normalize = True,dropna = False) * 100

customer_status
Active      67.67
Inactive    15.53
Closed      10.72
Suspended    6.08
Name: proportion, dtype: float64

In [100]:
customers["country"].nunique()

29

In [101]:
customers["country"].value_counts(dropna = False)

country
India             17537
USA                9911
UK                 5046
Canada             3987
Germany            3979
Australia          3471
Singapore          2953
UAE                2947
United States       172
U.S.                170
GERMANY             169
singapore           163
United Kingdom      161
india               159
uae                 155
Ger                 154
uk                  153
CAN                 151
INDIA               147
U.K.                146
usa                 146
australia           145
Aus                 143
Emirates            142
Ind                 142
u.a.e               141
germany             139
SG                  139
canada              132
Name: count, dtype: int64

In [102]:
country_mapping = {
    'India': 'India', 'india': 'India', 'INDIA': 'India', 'Ind': 'India',
    'USA': 'United States', 'United States': 'United States', 'U.S.': 'United States', 'usa': 'United States',
    'UK': 'United Kingdom', 'United Kingdom': 'United Kingdom', 'uk': 'United Kingdom', 'U.K.': 'United Kingdom',
    'Canada': 'Canada', 'CAN': 'Canada', 'canada': 'Canada',
    'Germany': 'Germany', 'GERMANY': 'Germany', 'Ger': 'Germany', 'germany': 'Germany',
    'Australia': 'Australia', 'australia': 'Australia', 'Aus': 'Australia',
    'Singapore': 'Singapore', 'singapore': 'Singapore', 'SG': 'Singapore',
    'UAE': 'United Arab Emirates', 'uae': 'United Arab Emirates', 'Emirates': 'United Arab Emirates', 'u.a.e': 'United Arab Emirates'
}
customers["country"] = customers["country"].map(country_mapping)

In [103]:
customers["country"].value_counts(dropna = False)

country
India                   17985
United States           10399
United Kingdom           5506
Germany                  4441
Canada                   4270
Australia                3759
United Arab Emirates     3385
Singapore                3255
Name: count, dtype: int64

In [104]:
customers["gender"].nunique()

12

In [105]:
customers["gender"].value_counts(dropna = False)

gender
Male      23961
Female    23316
Other      2534
male        383
O           377
F           359
female      359
other       355
m           350
M           340
f           337
OTH         329
Name: count, dtype: int64

In [107]:
gender_mapping = {
    "Male" : "Male",
    "male" : "Male",
    "m" : "Male",
    "M" : "Male",

    "Female" : "Female",
    "F" : "Female",
    "female" : "Female",
    "f" : "Female",

    "Other" : "Other",
    "O" : "Other",
    "other" : "Other",
    "OTH" : "Other"
}
customers["gender"] = customers["gender"].map(gender_mapping)

In [108]:
customers["gender"].value_counts(dropna = False)

gender
Male      25034
Female    24371
Other      3595
Name: count, dtype: int64

In [109]:
customers["customer_id"].isna().sum()

np.int64(0)

In [110]:
customers["customer_id"].duplicated().sum()

np.int64(3000)

In [113]:
duplicate_customer_ids = customers.loc[
    customers["customer_id"].duplicated(keep=False),
    "customer_id"
]

duplicate_customer_ids.value_counts().head(20)

customer_id
CUST00001    2
CUST00031    2
CUST00038    2
CUST00050    2
CUST00056    2
CUST00066    2
CUST00078    2
CUST00082    2
CUST00083    2
CUST00098    2
CUST00114    2
CUST00171    2
CUST00188    2
CUST00192    2
CUST00230    2
CUST00261    2
CUST00275    2
CUST00300    2
CUST00302    2
CUST00310    2
Name: count, dtype: int64

In [114]:
customers[
    customers["customer_id"].isin(duplicate_customer_ids)
].sort_values("customer_id")

,customer_id,age,gender,country,employment_type,income,account_type,signup_date,customer_status
0,CUST00001,35.00,Male,Singapore,Business Owner,"2,055,034.45",Current,2024-02-02,Inactive
51797,CUST00001,35.00,Male,Singapore,Business Owner,"2,055,034.45",Current,2024-02-02,Inactive
30,CUST00031,35.00,Male,United States,Employed,"1,110,899.11",Savings,2026-03-18,Inactive
50914,CUST00031,35.00,Male,United States,Employed,"1,110,899.11",Savings,2026-03-18,Inactive
37,CUST00038,19.00,Male,Germany,Employed,"1,599,450.29",Savings,2026-01-08,Closed
...,...,...,...,...,...,...,...,...,...
52697,CUST49976,25.00,Female,Germany,Employed,"752,651.07",NaN,2024-02-09,Inactive
49978,CUST49979,18.00,Female,Australia,Employed,"543,204.21",Salary,2026-02-22,Active
52071,CUST49979,18.00,Female,Australia,Employed,"543,204.21",Salary,2026-02-22,Active
49991,CUST49992,20.00,Other,Canada,Employed,"520,615.98",Current,2027-04-29,Active
51863,CUST49992,20.00,Other,Canada,Employed,"520,615.98",Current,2027-04-29,Active

In [115]:
customers.duplicated().sum()

np.int64(3000)

In [116]:
customers = customers.drop_duplicates().reset_index(drop=True)

In [117]:
customers.shape

(50000, 9)

In [118]:
future_signup_mask = customers["signup_date"] > pd.Timestamp.today()

future_signup_mask.sum()

np.int64(2992)

In [119]:
customers.loc[
    future_signup_mask,
    "signup_date"
].describe()

count                          2992
mean     2027-02-20 02:13:18.930481
min             2026-08-21 00:00:00
25%             2026-11-20 00:00:00
50%             2027-02-21 00:00:00
75%             2027-05-22 00:00:00
max             2027-08-19 00:00:00
Name: signup_date, dtype: object

In [120]:
customers.loc[
    ~future_signup_mask,
    "signup_date"
].describe()

count                         47008
mean     2024-10-24 14:35:51.667801
min             2023-01-01 00:00:00
25%             2023-11-28 00:00:00
50%             2024-10-24 00:00:00
75%             2025-09-21 00:00:00
max             2026-08-20 00:00:00
Name: signup_date, dtype: object

In [121]:
customers.loc[
    future_signup_mask,
    "signup_date"
] = pd.NaT

In [122]:
customers["signup_date"].isna().sum()

np.int64(2992)

In [123]:
customers["signup_date"].min()
customers["signup_date"].max()

Timestamp('2026-08-20 00:00:00')

In [124]:
customers.isnull().sum()

customer_id           0
age                   0
gender                0
country               0
employment_type       0
income                0
account_type       2222
signup_date        2992
customer_status       0
dtype: int64

In [125]:
customers.duplicated().sum()

np.int64(0)

In [126]:
customers["age"].min(), customers["age"].max()

(np.float64(18.0), np.float64(58.0))

In [127]:
customers["income"].min()

np.float64(20072.66)

In [130]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 7 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      150000 non-null  str
 1   customer_id         150000 non-null  str
 2   payment_date        150000 non-null  str
 3   amount              147000 non-null  float64
 4   payment_mode        145000 non-null  str
 5   transaction_status  150000 non-null  str
 6   transaction_type    147500 non-null  str
dtypes: float64(1), str(6)
memory usage: 14.9 MB

In [131]:
transactions["payment_date"] = pd.to_datetime(transactions["payment_date"],errors = "coerce")

In [132]:
transactions["payment_date"].dtype

dtype('<M8[us]')

In [133]:
transactions.isnull().sum()

transaction_id           0
customer_id              0
payment_date             0
amount                3000
payment_mode          5000
transaction_status       0
transaction_type      2500
dtype: int64

In [134]:
transactions.isnull().mean() * 100

transaction_id       0.00
customer_id          0.00
payment_date         0.00
amount               2.00
payment_mode         3.33
transaction_status   0.00
transaction_type     1.67
dtype: float64

In [135]:
transactions["amount"].describe()

count   147,000.00
mean      2,174.83
std       5,418.74
min     -99,900.00
25%         735.88
50%       1,471.53
75%       2,913.33
max      98,235.29
Name: amount, dtype: float64

In [138]:
invalid_amount_mask = ( 
    (transactions["amount"] < 0))
invalid_amount_mask.sum()

np.int64(760)

In [140]:
transactions.loc[
    ~invalid_amount_mask,
    "amount"].describe()

count   146,240.00
mean      2,452.72
std       3,208.11
min           0.00
25%         744.62
50%       1,480.55
75%       2,924.14
max      98,235.29
Name: amount, dtype: float64

In [145]:
invalid_amount_index = transactions.index[invalid_amount_mask]
transactions.loc[invalid_amount_index,"amount"] = np.nan
amount_median = transactions["amount"].median()
transactions["amount"] = transactions["amount"].fillna(amount_median)

In [146]:
transactions["amount"].describe()

count   150,000.00
mean      2,428.35
std       3,171.29
min           0.00
25%         760.21
50%       1,480.55
75%       2,868.80
max      98,235.29
Name: amount, dtype: float64

In [148]:
transactions["payment_mode"].value_counts(dropna = False)

payment_mode
UPI                98692
Cash               25411
Digital Wallets     8460
Cards               5611
NaN                 5000
Cheque              1457
Bank Transfer       1369
debit card           348
card                 343
digital wallet       342
cash                 339
cheque               339
BankTransfer         339
UPI Payment          336
upi                  333
credit card          332
Cheque Payment       330
bank transfer        312
wallet               307
Name: count, dtype: int64

In [149]:
transactions["payment_mode"].nunique()

18

In [150]:
transactions["payment_mode"].value_counts(normalize = True,dropna = False) * 100

payment_mode
UPI               65.79
Cash              16.94
Digital Wallets    5.64
Cards              3.74
NaN                3.33
Cheque             0.97
Bank Transfer      0.91
debit card         0.23
card               0.23
digital wallet     0.23
cash               0.23
cheque             0.23
BankTransfer       0.23
UPI Payment        0.22
upi                0.22
credit card        0.22
Cheque Payment     0.22
bank transfer      0.21
wallet             0.20
Name: proportion, dtype: float64

In [152]:
payment_mode_mapping = {
     "UPI": "UPI", "UPI Payment": "UPI", "upi": "UPI",
    "Cash": "Cash", "cash": "Cash",
    "Digital Wallets": "Digital Wallet", "digital wallet": "Digital Wallet", "wallet": "Digital Wallet",
    "Cards": "Card", "debit card": "Card", "card": "Card", "credit card": "Card",
    "Cheque": "Cheque", "cheque": "Cheque", "Cheque Payment": "Cheque",
    "Bank Transfer": "Bank Transfer", "BankTransfer": "Bank Transfer", "bank transfer": "Bank Transfer",
}
transactions["payment_mode"] = transactions["payment_mode"].map(payment_mode_mapping)

In [153]:
transactions["payment_mode"].value_counts(dropna = False)

payment_mode
UPI               99361
Cash              25750
Digital Wallet     9109
Card               6634
NaN                5000
Cheque             2126
Bank Transfer      2020
Name: count, dtype: int64

In [154]:
"Unknown" in transactions["payment_mode"].unique()

False

In [155]:
transactions["payment_mode"] = transactions["payment_mode"].fillna("Unknown")

In [157]:
transactions["payment_mode"].value_counts(dropna = False)

payment_mode
UPI               99361
Cash              25750
Digital Wallet     9109
Card               6634
Unknown            5000
Cheque             2126
Bank Transfer      2020
Name: count, dtype: int64

In [158]:
transactions["transaction_type"].value_counts(dropna = False)

transaction_type
Purchase        50473
Bill Payment    29015
Transfer        21740
Withdrawl       17191
Deposit         14389
Refund           7258
Subscription     4553
NaN              2500
TRANSFER          222
transfer          205
subscription      202
Bill payment      195
WITHDRAWAL        195
purchase          194
PURCHASE          193
DEPOSIT           190
SUBSCRIPTION      189
deposit           187
BILL PAYMENT      185
refund            184
bill payment      182
withdrawal        181
REFUND            177
Name: count, dtype: int64

In [160]:
transactions["transaction_type"].nunique()

22

In [163]:
transaction_mapping = {
    "Purchase": "Purchase",
    "purchase": "Purchase",
    "PURCHASE": "Purchase",

    "Bill Payment": "Bill Payment",
    "Bill payment": "Bill Payment",
    "BILL PAYMENT": "Bill Payment",
    "bill payment": "Bill Payment",

    "Transfer": "Transfer",
    "TRANSFER": "Transfer",
    "transfer": "Transfer",

    "Withdrawl": "Withdrawal",
    "WITHDRAWAL": "Withdrawal",
    "withdrawal": "Withdrawal",

    "Deposit": "Deposit",
    "DEPOSIT": "Deposit",
    "deposit": "Deposit",

    "Refund": "Refund",
    "refund": "Refund",
    "REFUND": "Refund",

    "Subscription": "Subscription",
    "subscription": "Subscription",
    "SUBSCRIPTION": "Subscription"
}
transactions["transaction_type"] = transactions["transaction_type"].map(transaction_mapping)

In [169]:
transactions["transaction_type"].isnull().sum()

np.int64(0)

In [164]:
transactions["transaction_type"].value_counts(dropna = False)

transaction_type
Purchase        50860
Bill Payment    29577
Transfer        22167
Withdrawal      17567
Deposit         14766
Refund           7619
Subscription     4944
NaN              2500
Name: count, dtype: int64

In [165]:
"Unkown" in transactions["transaction_type"].unique()

False

In [167]:
transactions["transaction_type"] = transactions["transaction_type"].fillna("Unknown")

In [168]:
transactions["transaction_type"].value_counts(dropna = False)

transaction_type
Purchase        50860
Bill Payment    29577
Transfer        22167
Withdrawal      17567
Deposit         14766
Refund           7619
Subscription     4944
Unknown          2500
Name: count, dtype: int64

In [170]:
transactions.isnull().sum()

transaction_id        0
customer_id           0
payment_date          0
amount                0
payment_mode          0
transaction_status    0
transaction_type      0
dtype: int64

In [173]:
transactions.duplicated().sum()

np.int64(0)

In [174]:
transactions["customer_id"].isin(
    customers["customer_id"]
)

0         True
1         True
2         True
3         True
4         True
          ...
149995    True
149996    True
149997    True
149998    True
149999    True
Name: customer_id, Length: 150000, dtype: bool

In [175]:
(~transactions["customer_id"].isin(
    customers["customer_id"]
)).sum()

np.int64(0)

In [180]:
future_payment_dates = transactions["payment_date"] > pd.Timestamp.today()
future_payment_dates.sum()

np.int64(63748)

In [181]:
transactions.loc[
    future_payment_dates,
    "payment_date"].describe()

count                         63748
mean     2027-08-11 23:57:32.268306
min             2026-08-21 00:00:00
25%             2027-01-09 00:00:00
50%             2027-06-25 00:00:00
75%             2028-02-09 00:00:00
max             2029-08-13 00:00:00
Name: payment_date, dtype: object

In [182]:
transactions.loc[
    ~future_payment_dates,
    "payment_date"].describe()

count                         86252
mean     2025-05-23 08:13:16.698047
min             2023-01-06 00:00:00
25%             2024-10-15 00:00:00
50%             2025-07-13 00:00:00
75%             2026-02-08 00:00:00
max             2026-08-20 00:00:00
Name: payment_date, dtype: object

In [183]:
transactions.loc[
    future_payment_dates,
    "payment_date"] = pd.NaT

In [184]:
transactions["payment_date"].isnull().sum()

np.int64(63748)

In [185]:
transactions.isnull().sum()

transaction_id            0
customer_id               0
payment_date          63748
amount                    0
payment_mode              0
transaction_status        0
transaction_type          0
dtype: int64

In [186]:
transactions.duplicated().sum()

np.int64(0)

In [198]:
customers.to_csv("E:/General_DS_project/Data/Processed/Customers_clean.csv",index = False)
transactions.to_csv("E:/General_DS_project/Data/Processed/Transactions_clean.csv",index = False)

In [188]:
transactions["transaction_status"].value_counts(dropna = False)

transaction_status
Success       109409
Failed         14792
Refunded       14437
Pending         7362
success          423
PROCESSING       421
CANCELLED        416
pending          414
REFUNDED         409
FAIL             404
failed           385
cancelled        382
SUCCESS          378
refunded         368
Name: count, dtype: int64

In [189]:
status_mapping = {
    "Success": "Success", "success": "Success", "SUCCESS": "Success",
    "Failed": "Failed", "failed": "Failed", "FAIL": "Failed",
    "Pending": "Pending", "pending": "Pending", "PROCESSING": "Pending",
    "Refunded": "Refunded", "refunded": "Refunded", "REFUNDED": "Refunded",
    "Cancelled": "Cancelled", "cancelled": "Cancelled", "CANCELLED": "Cancelled"
}
transactions["transaction_status"] = transactions["transaction_status"].map(status_mapping)
transactions["transaction_status"].value_counts(dropna=False)

transaction_status
Success      110210
Failed        15581
Refunded      15214
Pending        8197
Cancelled       798
Name: count, dtype: int64

In [190]:
invalid_amount_mask = transactions["amount"].notna() & (transactions["amount"] <= 0)
print(f"Invalid amounts (<= 0): {invalid_amount_mask.sum()}")

transactions.loc[invalid_amount_mask, "amount"] = np.nan
amount_median = transactions["amount"].median()
transactions["amount"] = transactions["amount"].fillna(amount_median)

Invalid amounts (<= 0): 1500

In [193]:
customer_signups = customers.set_index("customer_id")["signup_date"]
tx_signup_dates = transactions["customer_id"].map(customer_signups)
invalid_date_order = transactions["payment_date"] < tx_signup_dates
print(f"Transactions before signup date: {invalid_date_order.sum()}")

Transactions before signup date: 5

In [192]:
transactions = transactions.drop_duplicates().reset_index(drop=True)
transactions = transactions.dropna(subset=["payment_date"]).reset_index(drop=True)

In [196]:
transactions = transactions[~invalid_date_order].reset_index(drop=True)

In [197]:
customer_signups = customers.set_index("customer_id")["signup_date"]
tx_signup_dates = transactions["customer_id"].map(customer_signups)
invalid_date_order = transactions["payment_date"] < tx_signup_dates
print(f"Transactions before signup date: {invalid_date_order.sum()}")

Transactions before signup date: 0

## Activity Logs Data Inspection

In [ ]:
activity_logs.shape

In [ ]:
activity_logs.info()

In [ ]:
activity_logs.head()

In [ ]:
activity_logs.describe()

In [ ]:
activity_logs.describe(include='object')

In [ ]:
activity_logs.isnull().sum()

In [ ]:
activity_logs.isnull().mean() * 100

In [ ]:
activity_logs.duplicated().sum()

In [ ]:
activity_logs['activity_type'].value_counts(dropna=False)

In [ ]:
activity_logs['device_type'].value_counts(dropna=False)

In [ ]:
activity_logs['platform'].value_counts(dropna=False)

In [ ]:
activity_logs["customer_id"].nunique()

In [ ]:
activity_logs["activity_timestamp"].head()